exclude: 'node_modules|.git'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        # Needed because of the unsafe mermaid extension support in the mkdocs
        # yaml configuration file
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.9
    hooks:
      # Run the Ruff linter.
      - id: ruff
      # Run the Ruff formatter.
      - id: ruff-format
