exclude: 'node_modules|.git'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        # Needed because of the unsafe mermaid extension support in the mkdocs
        # yaml configuration file
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.2
    hooks:
      # Run the Ruff linter.
      - id: ruff
        args: [ '--fix' ]
      # Run the Ruff formatter.
      - id: ruff-format

  # grammar checker for /docs content
  - repo: https://github.com/errata-ai/vale
    rev: v3.12.0
    hooks:
      - id: vale
        name: vale sync
        pass_filenames: false
        args: [sync]
      - id: vale
        args: [--output=line, --minAlertLevel=error]
