exclude: 'node_modules|.git'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        # Needed because of the unsafe mermaid extension support in the mkdocs
        # yaml configuration file
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff
        args: ["--fix", "--config=pyproject.toml"]
      - id: ruff-format
        args: ["--config=pyproject.toml"]

  # grammar checker for /docs content
  # - repo: https://github.com/errata-ai/vale
  #   rev: v3.13.0
  #   hooks:
  #     # - id: vale
  #     #   name: vale sync
  #     #   pass_filenames: false
  #     #   args: [sync]
  #     - id: vale
  #       pass_filenames: true
  #       args: [--output=line, --minAlertLevel=error]

  - repo: https://github.com/semgrep/pre-commit
    rev: 'v1.153.1'
    hooks:
      - id: semgrep
        entry: semgrep
        # or see https://semgrep.dev/explore to select a ruleset and copy its URL
        args: ['--config', 'development/frappe-semgrep-rules/rules', '--error', '--skip-unknown-extensions']
        additional_dependencies: ['attrs']
