[project]
name = "fossunited"
authors = [
    { name = "FOSSUnited", email = "developers@fossunited.org"}
]
description = "Built on Frappe"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "razorpay~=1.4.2",
    "PyGithub~=2.3.0",
    "Faker~=27.0.0",
    "Pillow~=11.0.0",
    "ics~=0.7.2",
    "pre-commit>=4.2.0",
    "tatsu<5.10.0",
]

[project.optional-dependencies]
dev = [
  "pre-commit==4.2.0",
  "frappe-bench>=5.25.9",
  "ruff==0.12.5",
  "black==25.1.0",
  "basedpyright>=1.31.0",
  "python-lsp-server>=1.13.0",
  "djlint>=1.36.4",
  "ty>=0.0.1a25",
  "semgrep>=1.121.0",
]
docs = [
    "zensical>=0.0.23",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

[tool.ruff]
line-length = 99
fix = true
[tool.ruff.lint]
select = ["F", "E", "W", "I", "Q"] # from frappe
# ^ add more rules as well? RUF, UP and more?
ignore = ["F722", "F821"]
[tool.ruff.lint.per-file-ignores]
"**/doctype/**/*.py" = ["F821", "F722"]
"fossunited/www/fosshack/results/index.py" = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true


[tool.ty.rules]
possibly-unresolved-reference = "warn"
division-by-zero = "ignore"

[tool.ty.environment]
extra-paths = ["../frappe/"]

[tool.basedpyright]
extraPaths = ["../frappe/"]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
fossunited = { workspace = true }

[dependency-groups]
dev = [
    "fossunited[dev,docs]",
]
