name: 🐞️ Bug Report
description: File a bug report/issue
title: "[BUG] <title>"
labels: [Bug]

body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      example:
      - **Device**: [e.g. Desktop, Mobile(Pixel 7)]
      - **OS**: [e.g. Debian GNU/Linux 12, Fedora 34]
      - **Browser**: [e.g. firefox, safari]
    value: |
      - Device:
      - OS:
      - Browser:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
