site_name: FOSS United Knowledge Base
site_description: Comprehensive documentation and resources for the FOSS United platform and community.
copyright: Copyright &copy; 2021 - 2025 FOSS United Foundation
# site_url: https://docs.fossunited.org
repo_url: https://github.com/fossunited/fossunited
edit_uri: edit/develop/docs/docs/

nav:
  - Home: index.md

  - Your Profile:
      - Create Your Profile: create-profile.md
      - Manage Your Profile: manage-profile.md
      - Request Personal Data: request-data.md
      - Delete Personal Data: delete-data.md

  - Events & Participation:
      - Creating an Event: create-event.md
      - Event RSVPs: event-rsvp.md
      - Attending Events: attend-event.md
      - Event Call for Proposals (CFP): event-proposals.md
      - Managing Event Proposals: event-cfp.md
      - Reviewing Proposals: reviewing-proposals.md
      - Creating Event Schedule: event-schedule.md
      - Event Attendees Communication: event-attendees.md
      - What to Do at the Event: event.md

  - Volunteering:
      - Volunteering Overview: volunteering.md
      - Volunteering Perks: volunteering-perks.md
      - Marketing Events on Social Media: social-media.md
      - Telegram & Communication Channels: telegram.md

  - What We Do:
      - Initiatives Overview: initiative.md
      - FOSS Clubs: club.md
      - Grants Program: grants.md
      - People Behind FOSS United: people.md
      - Principles & Values: principles.md
      - FOSS Philosophy: foss.md
      - Speech & Presentations: speech.md
      - RSS & News: rss.md

  - Development & Documentation:
      - Platform Development: development.md
      - Documentation Guide: documentation.md
      - Project Management: project-management.md
      - Code Contributions: code-contributions.md
      - Architecture Overview: architecture.md
      - Changelog: changelog.md


theme:
  name: material
  logo: ./assets/fossunited-white.svg
  favicon: ./assets/fossunited-white.svg
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.diagram
    - navigation.footer
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: green
      accent: teal
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: green
      accent: light-green
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - glightbox
  - search:

extra_css:
  - assets/custom.css

extra:
  generator: true
  social:
    - icon: fontawesome/brands/discourse
      link: https://forum.fossunited.org/
    - icon: fontawesome/brands/telegram
      link: https://t.me/fossunited
    - icon: fontawesome/brands/mastodon
      link: https://mas.to/@fossunited
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fossunited.mas.to.ap.brid.gy
    - icon: fontawesome/brands/twitter
      link: http://x.com/fossunited
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/fossunited
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/company/fossunited
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fossunited
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/fossunited
    - icon: fontawesome/solid/envelope
      link: mailto:developers@fossunited.org

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
