site_name: FOSS United Platform / Docs

nav:
  - Home: index.md
  - Building your Profile:
      - Create your Profile: create-profile.md
      - Manage your Profile: manage-profile.md
      - Request personal data: request-data.md
      - Delete personal data: delete-data.md
  - Participating in the Community:
      - RSVP to an event: attend-event.md
      - Call for Proposals (CFP): event-proposals.md
  - Volunteer Guide:
      - Volunteering: volunteering.md
      - Event management: create-event.md
      - Manage event RSVPs: event-rsvp.md
      - Manage event proposals: event-cfp.md
      - Reviewing proposals: reviewing-proposals.md
      - Creating the event schedule: event-schedule.md

theme:
  name: material
  logo: ./assets/fossunited-white.svg
  favicon: ./assets/fossunited-white.svg
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: green
      accent: teal
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: green
      accent: light-green
  font:
    text: Inter

plugins:
  - glightbox
