name: spell_grammar
on:
  pull_request:

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get list of changed files
        id: changed_files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only --diff-filter=ACMR origin/${{ github.base_ref }}...${{ github.head_ref }} | grep -E '\.md$' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run Vale only on changed files
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: ${{ env.CHANGED_FILES }}
